# Site
name: 'Blog'
description: 'Best dropshipping agent in China-Nichepik'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'nichepik'
email: 'info@promaxsourcing.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  
authors:
    ray:
      name:           Ray
      site:           https://nichepik.com
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Ray,From Nichepik and will help you scale your business safe and stable"
      email:          info@promaxsourcing.com
      twitter:        #

    merry:
      name:           Merry
      site:           https://nichepik.com
      avatar:         assets/images/avatar2.jpg
      bio:            "Expert on global supply chain management, Grow your business world wide"
      email:          info@promaxsourcing.com
      twitter:        #
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ray
      avatar: assets/images/avatar1.jpg
      categories: "Dropshipping"
      tags: ""
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
# Do not update files in below folder when update site
keep_files: [assets, _includes, _layouts,_pages, _site, _posts]
#keep_files: [assets]
